server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /multitrack-player/;
  }

  location /multitrack-player/ {
    try_files $uri $uri/ /multitrack-player/index.html;
  }
}